name: Document Submit Latency Alert
on:
  repository_dispatch:
    types: [prometheus_alert]

env:
  AZURE_RESOURCE_GROUP: psod-sre-monitoring-observability
  AZURE_LOCATION: westeurope

jobs:
  handle-alert:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Parse alert
      id: parse
      shell: pwsh
      run: |
        $alert =  '${{ toJson(github.event.client_payload) }}' | ConvertFrom-Json
        echo "Alert name: $($alert.commonLabels.alertName)"
        echo "Severity: $($alert.commonLabels.severity)"
        $status = $alert.alerts[0].status
        echo "Status: $status"
        echo "status=$status" >> $env.GITHUB_OUTPUT

    - name: Debug
      shell: pwsh
      run: |
        echo "ALERT_STATUS: $($env:ALERT_STATUS)"
      env:
        ALERT_STATUS: ${{ steps.parse.output.status == firing }} 

    - name: Azure Login
      uses: azure/login@v1
      if: steps.parse.output.status == 'firing'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Reset feature flag
      uses: azure/cli@v2
      if: steps.parse.output.status == 'firing'
      with:
        inlineScript: |
          az account show
          az appconfig list -o table
          az appconfig kv set -n fulfilment-app --key 'Fulfilment:AuthSettings:UseExperimentalIdp' --value 'false' --yes

