name: Document Submit Latency Alert
on:
  repository_dispatch:
    types: [prometheus_alert]

env:
  AZURE_RESOURCE_GROUP: psod-sre-monitoring-observability
  AZURE_LOCATION: westeurope

jobs:
  handle-alert:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Debug
      shell: pwsh
      run: |
        $alert =  '${{ toJson(github.event.client_payload) }}' | ConvertFrom-Json
        echo "Alert labels: $($alert.commonLabels)"
        echo "Alert status: $($alert.alerts[0].status)"

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Reset feature flag
      uses: azure/cli@v2
      with:
        inlineScript: |
          az account show
          az appconfig list -o table
          az appconfig kv set -n fulfilment-app --key 'Fulfilment:AuthSettings:UseExperimentalIdp' --value 'false' --yes

