name: Document Submit Latency Alert
on:
  repository_dispatch:
    types: [prometheus_alert]

jobs:
  handle-alert:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Parse Alert Data
      id: parse
      shell: pwsh
      run: |
        $alert =  '${{ toJson(github.event.client_payload) }}' | ConvertFrom-Json
        $alert