name: Document Submit Latency Alert
on:
  repository_dispatch:
    types: [prometheus_alert]

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: my-resource-group
  AZURE_LOCATION: eastus

jobs:
  handle-alert:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Debug
      id: debug
      shell: pwsh
      run: |
        $alert =  '${{ toJson(github.event.client_payload) }}' | ConvertFrom-Json
        $alert

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        inlineScript: |
          az account show

