name: Document Submit Latency Alert
run-name: 'Document Submit Latency Alert: ${{ github.event.client_payload.alerts[0].status }}'

on:
  repository_dispatch:
    types: [DocumentSubmitLatency]

env:
  AZURE_RESOURCE_GROUP: psod-sre-monitoring-observability
  AZURE_LOCATION: westeurope

jobs:
  handle-alert:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Parse alert
      id: parse-alert
      shell: pwsh
      run: |
        $alert =  '${{ toJson(github.event.client_payload) }}' | ConvertFrom-Json
        echo "Alert name: $($alert.commonLabels.alertName)"
        echo "Severity: $($alert.commonLabels.severity)"
        echo "Status: $($alert.alerts[0].status)"

    - name: Azure Login
      if: github.event.client_payload.alerts[0].status == 'firing'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Reset feature flag
      if: github.event.client_payload.alerts[0].status == 'firing'
      uses: azure/cli@v2
      with:
        inlineScript: |
          az account show
          az appconfig list -o table
          az appconfig kv set -n fulfilment-app --key 'Fulfilment:AuthSettings:UseExperimentalIdp' --value 'false' --yes

